FROM moby/buildkit:v0.29.0 AS buildkit

FROM golang:1.25 AS runner-build
COPY . /src
WORKDIR /src
RUN go build -o /ci-runner ./cmd/ci-runner

FROM moby/buildkit:v0.29.0
RUN apk add --no-cache ca-certificates
COPY --from=runner-build /ci-runner /usr/bin/ci-runner
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
